import{S as d,i as c}from"./assets/vendor-BrddEoy-.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const f=t=>{const s=new URLSearchParams({key:"48301172-ef8913a37f764f18c5dbf5629",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`https://pixabay.com/api/?${s}`).then(o=>{if(!o.ok)throw new Error(o.status);return o.json()})},h=t=>`<div class="gallery">
                   <a href='${t.largeImageURL}'>
                   <img src='${t.webformatURL}' alt='${t.tags}'/>
                   </a>
                  <div class='comment-box'>
                    <p class='img-comment'><b class='img-comment-title'>Likes</b>: ${t.likes}</p>
                    <p class='img-comment'><b class='img-comment-title'>Views</b>: ${t.views}</p>
                    <p class='img-comment'><b class='img-comment-title'>Comments</b>: ${t.comments}</p>
                    <p class='img-comment'><b class='img-comment-title'>Downloads</b>: ${t.downloads}</p>
                  </div>
                </div>
                <button id="load-more" class="hidden">Load more</button>`,u=document.querySelector(".user-search"),l=document.querySelector("#input-search"),m=document.querySelector("#results"),i=document.querySelector("#loader-js");let p=new d(".gallery a",{captionsData:"alt",captionDelay:250});const g=t=>{t.preventDefault();const s=l.value.trim();if(!s){c.error({title:"Error",message:"The search field cannot be empty. Please try again!",position:"topRight"});return}m.innerHTML="",l.value="",i.classList.remove("hidden"),f(s).then(o=>{if(i.classList.add("hidden"),o.hits.length===0){c.warning({title:"No results",message:"No images found for your query!",position:"topRight"});return}m.innerHTML=o.hits.map(h).join(""),p.refresh()}).catch(o=>{i.classList.remove("hidden"),c.error({title:"Error",message:"An error occurred. Please try again!",position:"topRight"}),console.error(o)}).finally(()=>{u.reset(),i.classList.add("hidden")})};u.addEventListener("submit",g);
//# sourceMappingURL=index.js.map
