import{i as a,S as u}from"./assets/vendor-5ObWk2rO.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();function d(i,t,o,n,e,r){fetch(`https://pixabay.com/api/?key=${t.key}&q=${encodeURIComponent(i)}&image_type=${t.image_type}&orientation=${t.orientation}&safesearch=${t.safesearch}`).then(s=>{if(!s.ok)throw new Error(s.status);return s.json()}).then(s=>{if(o.classList.add("hidden"),s.hits.length===0){a.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}r(s.hits,n,e)}).catch(s=>{o.classList.add("hidden"),a.error({title:"Error",message:"Sorry, an error occurred. Please try again!",position:"topRight"}),console.error(s)})}function f(i,t,o){const n=i.map(e=>`<li class='gallery-item'>
              <a class='gallery-link' href='${e.largeImageURL}'>
              <img class='gallery-img' src='${e.webformatURL}' alt='${e.tags}' />
              </a>
              <div class='comment-box'>
                <p class='img-comment'><b class='img-comment-title'>Likes</b>: ${e.likes}</p>
                <p class='img-comment'><b class='img-comment-title'>Views</b>: ${e.views}</p>
                <p class='img-comment'><b class='img-comment-title'>Comments</b>: ${e.comments}</p>
                <p class='img-comment'><b class='img-comment-title'>Downloads</b>: ${e.downloads}</p>
              </div>
            </li>`).join("");t.innerHTML=n,o?o.refresh():o=new u(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250,nav:!0})}const p=document.querySelector(".user-search"),c=document.querySelector("#input-search"),l=document.querySelector("#results"),m=document.querySelector("#loader-js"),h={key:"48301172-ef8913a37f764f18c5dbf5629",image_type:"photo",orientation:"horizontal",safesearch:!0};let g=null;p.addEventListener("submit",i=>{i.preventDefault();const t=c.value.trim();if(t===""){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}l.innerHTML="",m.classList.remove("hidden"),d(t,h,m,l,g,f),c.value=""});
//# sourceMappingURL=index.js.map
